# Generated by Django 3.1.1 on 2020-10-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_tarea_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creación',
            field=models.DateField(default='2020-10-14'),
        ),
    ]
